name: CD

on:
  push:
    branches:
      - main
      - release/*

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get Node Version
        id: nvm
        run: echo ::set-output name=version::$(cat .nvmrc)
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.version }}'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
